Enable multi-architecture docker image builds
nginx-proxy/nginx-proxy pull request #1470
Opened 2020-07-13 11:40 UTC by tkw1536

Previously, the Dockerfile downloaded 'docker-gen' and 'forego' binaries during build time. This caused a problem as it hard-coded the amd64 architecture for the images.

This PR updates both 'Dockerfile' and 'Dockerfile.alpine' to build the `forego` and `docker-gen` executables from source instead of downloading binaries directly. This is achieved using multi-stage builds [1]. Two separate stages first build the binaries, and are then copied over to the final stage.

The advantage of this change is two-fold: First, it enables building this image on architectures other than amd64. Second it adds trust by not adding external binaries to the docker image.

This modified version passes the tests both a linux desktop (`amd64`) as well as a raspberry pi (`armv7`) with some caveats:

- On `armv7`, a modified version of the `jwilder/docker-gen` image is required. See jwilder/docker-gen#327. 
- The `test_dhparam_is_generated_if_missing` test fails. This also doesn't currently pass on master. See #1468. 

See also:
- #1317 and #1370, #1297: These issues request an arm version of the image. Together with publishing arm images on DockerHub, this PR should fix all of them. 
- #1262, #1071: Both these PRs make a seperate Dockerfile for the arm architecture. This PR is more general, in that it doesn't assume a specific architecture. In particular any architecture supported by the golang, debian and alpine base images can be used. 

[1] https://docs.docker.com/develop/develop-images/multistage-build/

2020-08-01 17:05 UTC, dustinrue commented
I'd also really like to see this implemented

2020-10-10 08:21 UTC, awehrfritz commented
Excellent initiative and nice implementation! @jwilder is there a chance to get this merged into master or do you have any objections to this?

2020-10-11 09:26 UTC, tkw1536 commented
I have yet to hear any feedback from @jwilder. I have nonetheless rebased this onto the current master, I only had to update the nginx version number.

2020-12-24 03:36 UTC, plonkus commented
This PR helped me get up and running on the Apple M1 processor. Thank you @tkw1536

2020-12-31 15:09 UTC, kipusoep commented
So any instructions to start using this on armv7?
I tried to build the docker image from your repo, which works, but still got errors running the image.
Then I saw your note about `jwilder/docker-gen`, how do I incorporate that fix in this fix as well?

2021-01-13 17:43 UTC, tkw1536 commented
@kipusoep This image should just build and run on armv7, it did when I ran the tests under qemu locally. What is the error you are getting?

2021-02-06 06:56 UTC, danil-smirnov commented
I think this should be considered, very useful change

2021-02-06 08:39 UTC, danil-smirnov commented
@tkw1536 I believe there is an issue with this branch.

Original @jwilder code sets `DOCKER_GEN_VERSION` environment variable, which `letsencrypt-nginx-proxy-companion` product relies on, see

https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/app/functions.sh#L241

After your multistage build this environment variable appeared unset, so `letsencrypt-nginx-proxy-companion` container fails.

2021-02-06 12:54 UTC, tkw1536 commented
@danil-smirnov  I'm not convinced this is a problem. If you look at the diff of the PRs, neither of the old Dockerfiles set this variable and they seem to work fine on `linux/amd64` for many people.

2021-02-06 13:47 UTC, danil-smirnov commented
@tkw1536 Okay, let's look at the old Dockerfiles:

https://github.com/nginx-proxy/nginx-proxy/blob/master/Dockerfile#L21
https://github.com/nginx-proxy/nginx-proxy/blob/master/Dockerfile.alpine#L18

Both set this variable so `letsencrypt-nginx-proxy-companion` can rely on them.

I've added the line `ENV DOCKER_GEN_VERSION 0.7.4` to my custom image and `letsencrypt-nginx-proxy-companion` can started working after the fix.

2021-02-06 13:59 UTC, tkw1536 commented
Oh you are correct. I forgot to read that `letsencrypt-nginx-proxy-companion` relies on this variable. 
I will add it to the branch.

2021-02-06 14:14 UTC, tkw1536 commented
Added it to the branch, thanks @danil-smirnov.
Not all we have to do is wait for this PR to be merged.

2021-02-13 17:20 UTC, severin-bruhat commented
Hello, any update on this one?
Thanks

2021-02-14 05:09 UTC, awehrfritz commented
> Now all we have to do is wait for this PR to be merged.

We are waiting already for quite a while... more than half a year. It's a bit worrying that the last commit in this repository is from Oct 2020. Not sure who controls this repository or who else other than @jwilder has is able to merge PRs.

2021-03-21 11:33 UTC, tkw1536 commented
Rebased onto the current master. With a new maintainer I would be happy to see this merged.

2021-04-01 11:34 UTC, buchdag requested changes
I'd rather use directly `FROM golang:1.15.x AS gobuilder` rather than passing the base image version used with `ARG`, so that we can use `dependabot`. 

Other than that, looks good to me.

2021-04-01 11:58 UTC, tkw1536 commented
I've updated this pull request with the changes requested.

2021-04-01 12:42 UTC, buchdag commented
@tkw1536 could you do the same for the `FROM nginx:$NGINX_VERSION`, for the same reason (detection of dependencies versions by dependabot) ?

2021-04-01 13:56 UTC, tkw1536 commented
Done, updated. I don't think it's needed for `DOCKER_GEN_VERSION` or `FOREGO_VERSION`, as those are probably not covered by dependabot.

2021-04-01 17:07 UTC, buchdag approved these changes
LGTM

2021-04-01 17:08 UTC, merged

2021-04-01 23:32 UTC, buchdag commented
@tkw1536 if you spotted other arm related issue or PR that might be closed following the merging of this PR, don't hesitate to tag me on them.