Update docker-gen
nginx-proxy/nginx-proxy pull request #1585
Opened 2021-04-09 08:31 UTC by mikaelz

It was updated https://github.com/jwilder/docker-gen/releases/tag/0.7.5

I'm getting `no servers are inside upstream in /etc/nginx/conf.d/default.conf:58` I think it should have been fixed by https://github.com/jwilder/docker-gen/pull/336

2021-04-09 08:53 UTC, etu commented
I've been debugging this all morning and just landed on the PR https://github.com/jwilder/docker-gen/pull/336 to then find this update, very happy to see this getting fixed :joy:

2021-04-09 10:49 UTC, buchdag commented
@mikaelz this update introduced a regression (see https://github.com/nginx-proxy/nginx-proxy/issues/1548#issuecomment-815831420), so I don't want to update **nginx-proxy** to use **docker-gen** `0.7.5` just yet.

2021-04-09 21:28 UTC, tkw1536 requested changes
The same change should be applied to `Dockerfile.alpine` as well.

2021-04-09 23:40 UTC, buchdag commented
**docker-gen**'s version won't be updated until https://github.com/jwilder/docker-gen/pull/345 is merged in and a corresponding tag has been released.

2021-04-23 22:48 UTC, JamieMagee commented
`0.7.6` has been released: https://github.com/jwilder/docker-gen/releases/tag/0.7.6

2021-04-26 13:09 UTC, closed without merging