Support LOG_FORMAT env variable.
nginx-proxy/nginx-proxy pull request #2151
Opened 2023-01-26 17:45 UTC by vincent-herlemont

2023-01-26 19:37 UTC, rhansen requested changes
Thanks for the PR!

2023-01-26 19:37 UTC, rhansen commented on nginx.tmpl
> +log_format vhost '{{ $globals.log_format }}';
Given there is only one user of the value I don't think we need to store it in `$globals`.

```suggestion
log_format vhost '{{ or $globals.Env.LOG_FORMAT "$host $remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$upstream_addr\"" }}';
```

2023-01-26 19:37 UTC, rhansen commented on test/test_log_format.py
> +    r = nginxproxy.get("http://unknown.nginx-proxy.tld/port")
```suggestion
    r = nginxproxy.get("http://nginx-proxy.test/port")
```

2023-01-26 19:37 UTC, rhansen commented on test/test_log_format.py
> +    sut_container = docker_compose.containers.get("test_log_format_sut_1")
The container name should match the `container_name` value in the Docker compose file:

```suggestion
    sut_container = docker_compose.containers.get("sut")
```

2023-01-26 19:37 UTC, rhansen commented on test/test_log_format.yml
> +    VIRTUAL_HOST: web1.tld
Client requests to names containing `nginx-proxy` will have their DNS lookups hijacked during testing to point to the nginx-proxy container:

```suggestion
    VIRTUAL_HOST: nginx-proxy.text
```

2023-01-26 19:37 UTC, rhansen commented on test/test_log_format.yml
> +sut:
Specify the container name to guarantee you can successfully look it up from Python:

```suggestion
sut:
  container_name: sut
```

2023-01-26 19:37 UTC, rhansen commented on test/test_log_format.yml
> +    DEFAULT_HOST: web1.tld
No need to set `DEFAULT_HOST` if the hostname in the query matches.

```suggestion
```

2023-01-27 09:10 UTC, vincent-herlemont commented
@rhansen Thanks for the review, I applied your review.

2023-01-27 16:45 UTC, rhansen commented on test/test_log_format.yml
> +# GIVEN a webserver with VIRTUAL_HOST set to web1.tld
```suggestion
```

2023-01-27 16:45 UTC, rhansen commented on test/test_log_format.yml
> +# WHEN nginx-proxy runs with DEFAULT_HOST set to web1.tld
```suggestion
```

2023-01-27 17:26 UTC, rhansen approved these changes

2023-01-27 17:28 UTC, merged

2023-01-27 18:05 UTC, vincent-herlemont commented
@rhansen Thanks you! Did you know when is the next release with this feature is planned?

2023-01-27 18:55 UTC, rhansen commented
That's up to @buchdag, although you can use the `latest` label which tracks `main`.

I forgot about updating the documentation. Would you mind opening a PR that mentions this new feature in `README.md`?

2023-01-27 21:37 UTC, buchdag commented
@vincent-herlemont I'd like to have #1179 merged to complement #2146 before releasing a new version (and documentation for your PR's feature, as mentioned by @rhansen).

2023-01-27 22:19 UTC, vincent-herlemont commented
@rhansen @buchdag Ok, follow up the documentation for this PR's feature https://github.com/nginx-proxy/nginx-proxy/pull/2152.