build: get docker-gen from pre-built image
nginx-proxy/nginx-proxy pull request #2230
Opened 2023-04-30 14:40 UTC by buchdag

2023-04-30 18:39 UTC, rhansen commented
> The actual value of DOCKER_GEN_VERSION isn't important for acme-companion

If acme-companion doesn't care about the value, why does it need it to be set? Can we change acme-companion so we can leave it unset here?

2023-04-30 19:53 UTC, buchdag commented
It's the way acme-companion uses to make sure a given container is running docker-gen (it's a check made at startup of the container in order to exit early with a warning in case of misconfiguration).

We could possibly change it but that would be a breaking change as acme-version before this modification would cease to work with newer versions of nginx-proxy that don't have the environment variable.

I'd rather keep a legacy environment variable rather than introduce an unneeded breaking change for now.

2023-05-01 13:59 UTC, buchdag commented
To clarify, the goal of the PR is to simplify the Dockerfile, maintenance (now Dependabot will automatically pick up new releases of docker-gen), and speed-up the image build. I think keeping the `DOCKER_GEN_VERSION` environment variable for backward compatibility with acme-companion is an acceptable compromise.

That flimsy check acme-companion is doing comes from a time when both projects were maintained by a different set of people. I agree that it should ideally be replaced (or removed ?) but that's out of the scope of this PR.

2023-05-01 19:07 UTC, rhansen requested changes

2023-05-01 19:48 UTC, buchdag commented on .github/workflows/build-publish.yml
> +        run: echo "DOCKER_GEN_VERSION=$(grep -o -E 'nginxproxy/docker-gen:([0-9x\.]+)' Dockerfile | cut -d ':' -f2)" >> $GITHUB_ENV
That's a mistake.

2023-05-01 19:50 UTC, buchdag commented on .github/workflows/build-publish.yml
> +        run: echo "DOCKER_GEN_VERSION=$(grep -o -E 'nginxproxy/docker-gen:([0-9x\.]+)' Dockerfile | cut -d ':' -f2)" >> $GITHUB_ENV
Will do.

2023-05-01 19:50 UTC, buchdag commented on .github/workflows/build-publish.yml
> +        run: echo "DOCKER_GEN_VERSION=$(grep -o -E 'nginxproxy/docker-gen:([0-9x\.]+)' Dockerfile | cut -d ':' -f2)" >> $GITHUB_ENV
Will do.

2023-05-01 19:51 UTC, buchdag commented on Dockerfile
> +FROM nginxproxy/docker-gen:0.10.4-debian AS docker-gen
I think it would unfortunately.

2023-05-02 02:02 UTC, rhansen approved these changes

2023-05-02 03:21 UTC, merged